const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('.qa', { recursive: true });
  const http = require('node:http');
  const path = require('node:path');
  const server = http.createServer((request, response) => {
    const name = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const file = path.join(process.cwd(), name === '/' ? 'index.html' : name);
    const type = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp' }[path.extname(file)];
    if (!fs.existsSync(file)) { response.writeHead(404); response.end(); return; }
    response.setHeader('Content-Type', type || 'application/octet-stream');
    fs.createReadStream(file).pipe(response);
  });
  await new Promise(resolve => server.listen(8123, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_BROWSER ? { channel: process.env.PLAYWRIGHT_BROWSER } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const visit = async path => { await page.goto('http://127.0.0.1:8123/' + path); await page.waitForSelector('#navbar'); };
  await visit('');
  await page.screenshot({ path: '.qa/home-desktop.png', fullPage: true });
  assert.equal(await page.locator('h1').count(), 1);
  await page.locator('#navbar [data-site-search]').first().click();
  await page.locator('#global-search').fill('sonus');
  assert.equal(await page.locator('.command-result').count(), 1);
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => !document.querySelector('.command-dialog').open);
  assert.equal(await page.locator('.command-dialog').evaluate(el => el.open), false);
  await visit('reviews.html?category=pc');
  assert.equal(await page.locator('[data-review-card]:visible').count(), 1);
  await page.locator('#review-search').fill('nomatchxyz');
  assert.equal(await page.locator('[data-review-card]:visible').count(), 0);
  await page.locator('[data-reset-reviews]').click();
  assert.equal(await page.locator('[data-review-card]:visible').count(), 4);
  await visit('resources1.html');
  const save = page.locator('.save-resource').first();
  await save.click();
  assert.equal(await save.getAttribute('aria-pressed'), 'true');
  await page.reload(); await page.waitForSelector('#navbar');
  assert.equal(await page.locator('.save-resource').first().getAttribute('aria-pressed'), 'true');
  await page.locator('#saved-resources-only').check();
  assert.equal(await page.locator('.resource-item:visible').count(), 1);
  await page.locator('#saved-resources-only').uncheck();
  await page.locator('#resource-search').fill('nomatchxyz');
  assert.equal(await page.locator('.resource-item:visible').count(), 0);
  await visit('beanmouse-review.html');
  assert.ok(await page.locator('.article-contents a').count() > 1);
  await page.locator('.reading-tools button').click();
  assert.ok(await page.locator('body').evaluate(el => el.classList.contains('reading-focus')));
  await page.locator('.reading-tools button').click();
  await visit('contact.html');
  await page.route('https://formspree.io/**', route => route.fulfill({ status: 500, contentType: 'application/json', body: '{}' }));
  await page.locator('#form-name').fill('Site test');
  await page.locator('#form-email').fill('test@example.com');
  await page.locator('#form-subject').fill('Local verification');
  await page.locator('#form-message').fill('This is a local intercepted test request.');
  await page.locator('#contact-form button[type=submit]').click();
  await page.waitForSelector('.submission-error');
  assert.equal(await page.locator('#contact-form-success').isVisible(), false);
  await page.route('https://formspree.io/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' }));
  await page.locator('#contact-form button[type=submit]').click();
  await page.waitForSelector('#contact-form-success', { state: 'visible' });
  const files = fs.readdirSync('.').filter(name => name.endsWith('.html') && !['header.html', 'footer.html', 'template.html', 'components.html'].includes(name));
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 });
    for (const file of files) {
      await visit(file);
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2);
      if (overflow) console.log(await page.locator('body *').evaluateAll(nodes => nodes.filter(node => node.getBoundingClientRect().right > innerWidth + 2).map(node => [node.tagName, node.className, node.getBoundingClientRect().right]).slice(0, 12)));
      assert.equal(overflow, false, `Horizontal overflow on ${file} at ${width}px`);
      const broken = await page.locator('img').evaluateAll(images => images.filter(img => img.complete && !img.naturalWidth).map(img => img.getAttribute('src')));
      assert.deepEqual(broken, [], `Broken images on ${file}`);
    }
  }
  await visit('');
  await page.evaluate(async () => {
    for (const image of document.querySelectorAll('img')) image.loading = 'eager';
    await Promise.all([...document.images].map(image => image.decode().catch(() => {})));
  });
  await page.screenshot({ path: '.qa/home-mobile.png', fullPage: true });
  await page.locator('#mobile-menu-button').click();
  assert.equal(await page.locator('#mobile-menu').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#mobile-menu').isVisible(), false);
  await page.locator('[data-theme-toggle]').first().click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.reload(); await page.waitForSelector('#navbar');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => { Storage.prototype.getItem = () => { throw new Error('Storage blocked'); }; Storage.prototype.setItem = () => { throw new Error('Storage blocked'); }; });
  const blockedPage = await blocked.newPage();
  const blockedErrors = [];
  blockedPage.on('pageerror', error => blockedErrors.push(error.message));
  await blockedPage.goto('http://127.0.0.1:8123/');
  await blockedPage.waitForSelector('#navbar');
  await blockedPage.locator('#navbar [data-site-search]').first().click();
  assert.equal(await blockedPage.locator('.command-dialog').evaluate(el => el.open), true);
  assert.deepEqual(blockedErrors, []);
  await blocked.close();
  assert.deepEqual(errors, []);
  await browser.close();
  server.close();
  console.log(`PASS: search, reviews, saved resources, reading tools, contact failure/success, mobile menu, and ${files.length} pages at two viewport sizes.`);
})().catch(error => { console.error(error); process.exit(1); });
