const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('.qa', { recursive: true });
  const http = require('node:http');
  const path = require('node:path');
  const server = http.createServer((request, response) => {
    const name = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const file = path.join(process.cwd(), name === '/' ? 'index.html' : name);
    const type = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp' }[path.extname(file)];
    if (!fs.existsSync(file)) { response.writeHead(404); response.end(); return; }
    response.setHeader('Content-Type', type || 'application/octet-stream');
    fs.createReadStream(file).pipe(response);
  });
  await new Promise(resolve => server.listen(8123, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_BROWSER ? { channel: process.env.PLAYWRIGHT_BROWSER } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const visit = async path => { await page.goto('http://127.0.0.1:8123/' + path); await page.waitForSelector('#navbar'); };
  await visit('');
  await page.screenshot({ path: '.qa/home-desktop.png', fullPage: true });
  assert.equal(await page.locator('h1').count(), 1);
  await page.locator('#navbar [data-site-search]').first().click();
  await page.locator('#global-search').fill('sonus');
  assert.equal(await page.locator('.command-result').count(), 1);
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => !document.querySelector('.command-dialog').open);
  assert.equal(await page.locator('.command-dialog').evaluate(el => el.open), false);
  await visit('reviews.html?category=pc');
  assert.equal(await page.locator('[data-review-card]:visible').count(), 1);
  await page.locator('#review-search').fill('nomatchxyz');
  assert.equal(await page.locator('[data-review-card]:visible').count(), 0);
  await page.locator('[data-reset-reviews]').click();
  assert.equal(await page.locator('[data-review-card]:visible').count(), 4);
  await visit('resources1.html');
  const save = page.locator('.save-resource').first();
  await save.click();
  assert.equal(await save.getAttribute('aria-pressed'), 'true');
  await page.reload(); await page.waitForSelector('#navbar');
  assert.equal(await page.locator('.save-resource').first().getAttribute('aria-pressed'), 'true');
  await page.locator('#saved-resources-only').check();
  assert.equal(await page.locator('.resource-item:visible').count(), 1);
  await page.locator('#saved-resources-only').uncheck();
  await page.locator('#resource-search').fill('nomatchxyz');
  assert.equal(await page.locator('.resource-item:visible').count(), 0);
  await visit('setup.html');
  await page.waitForSelector('.desk-hotspot');
  assert.equal(await page.locator('.desk-hotspot').count(), 4);
  await page.locator('.desk-hotspot[aria-label="Explore headphones"]').click();
  assert.ok((await page.locator('.inspector-list').innerText()).includes('Sennheiser HD 580'));
  await page.locator('.inspector-tab', { hasText: 'Mice' }).click();
  assert.ok((await page.locator('.inspector-list').innerText()).includes('Pulsar X2 Crazylight Mini'));
  await page.locator('.photo-expand').click();
  assert.equal(await page.locator('.photo-dialog').evaluate(el => el.open), true);
  await page.locator('.photo-close').click();
  await page.locator('.setup-section-filter[data-section="audio"]').click();
  assert.equal(await page.locator('.inventory-section:not([hidden])').count(), 1);
  assert.equal(await page.locator('#audio').isVisible(), true);
  await page.evaluate(() => { navigator.clipboard.writeText = async text => { window.__copiedSpecs = text; }; });
  await page.locator('#copy-specs-btn').click();
  assert.ok((await page.evaluate(() => window.__copiedSpecs)).includes('FIIO K15'));
  assert.ok((await page.evaluate(() => window.__copiedSpecs)).includes('Pulsar X2 Crazylight Mini'));
  assert.ok(!(await page.evaluate(() => window.__copiedSpecs)).includes('Topping DX5'));
  await page.locator('.setup-section-filter[data-section="all"]').click();
  assert.equal(await page.locator('.inventory-section:not([hidden])').count(), 4);
  assert.equal(await page.locator('.audio-node').count(), 4);
  await page.evaluate(async () => {
    for (const image of document.querySelectorAll('img')) image.loading = 'eager';
    await Promise.all([...document.images].map(image => image.decode().catch(() => {})));
  });
  await page.screenshot({ path: '.qa/setup-desktop.png', fullPage: true });
  await visit('beanmouse-review.html');
  assert.ok(await page.locator('.article-contents a').count() > 1);
  await page.locator('.reading-tools button').click();
  assert.ok(await page.locator('body').evaluate(el => el.classList.contains('reading-focus')));
  await page.locator('.reading-tools button').click();
  await visit('contact.html');
  await page.route('https://formspree.io/**', route => route.fulfill({ status: 500, contentType: 'application/json', body: '{}' }));
  await page.locator('#form-name').fill('Site test');
  await page.locator('#form-email').fill('test@example.com');
  await page.locator('#form-subject').fill('Local verification');
  await page.locator('#form-message').fill('This is a local intercepted test request.');
  await page.locator('#contact-form button[type=submit]').click();
  await page.waitForSelector('.submission-error');
  assert.equal(await page.locator('#contact-form-success').isVisible(), false);
  await page.route('https://formspree.io/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' }));
  await page.locator('#contact-form button[type=submit]').click();
  await page.waitForSelector('#contact-form-success', { state: 'visible' });
  const files = fs.readdirSync('.').filter(name => name.endsWith('.html') && !['header.html', 'footer.html', 'template.html', 'components.html'].includes(name));
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 });
    for (const file of files) {
      await visit(file);
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2);
      if (overflow) console.log(await page.locator('body *').evaluateAll(nodes => nodes.filter(node => node.getBoundingClientRect().right > innerWidth + 2).map(node => [node.tagName, node.className, node.getBoundingClientRect().right]).slice(0, 12)));
      assert.equal(overflow, false, `Horizontal overflow on ${file} at ${width}px`);
      const broken = await page.locator('img').evaluateAll(images => images.filter(img => img.complete && !img.naturalWidth).map(img => img.getAttribute('src')));
      assert.deepEqual(broken, [], `Broken images on ${file}`);
    }
  }
  await visit('setup.html');
  await page.locator('.desk-hotspot[aria-label="Explore keyboards"]').click();
  assert.ok((await page.locator('.inspector-list').innerText()).includes('Geonworks Frog Mini'));
  await page.locator('.photo-expand').click();
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => !document.querySelector('.photo-dialog').open);
  assert.equal(await page.locator('.photo-expand').evaluate(el => document.activeElement === el), true);
  await page.screenshot({ path: '.qa/setup-mobile.png' });
  await page.locator('[data-theme-toggle]').first().click();
  await page.waitForFunction(() => getComputedStyle(document.querySelector('.inspector-list strong')).color === 'rgb(30, 41, 59)');
  await page.screenshot({ path: '.qa/setup-light.png' });
  await page.locator('[data-theme-toggle]').first().click();
  await visit('');
  await page.evaluate(async () => {
    for (const image of document.querySelectorAll('img')) image.loading = 'eager';
    await Promise.all([...document.images].map(image => image.decode().catch(() => {})));
  });
  await page.screenshot({ path: '.qa/home-mobile.png', fullPage: true });
  await page.locator('#mobile-menu-button').click();
  assert.equal(await page.locator('#mobile-menu').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#mobile-menu').isVisible(), false);
  await page.locator('[data-theme-toggle]').first().click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.waitForFunction(() => document.querySelector('#hero-scene').dataset.sceneState);
  assert.equal(await page.locator('#hero-scene').getAttribute('data-motion'), 'reduced');
  assert.equal(await page.locator('#scene-toggle').isVisible(), false);
  const motionContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'no-preference' });
  const motionPage = await motionContext.newPage();
  const motionErrors = [];
  motionPage.on('pageerror', error => motionErrors.push(error.message));
  motionPage.on('console', message => { if (message.type() === 'error' && /Shader|VALIDATE_STATUS|THREE/.test(message.text())) motionErrors.push(message.text()); });
  await motionPage.goto('http://127.0.0.1:8123/');
  await motionPage.waitForFunction(() => Number(document.querySelector('#hero-scene').dataset.frames) > 5);
  assert.equal(await motionPage.locator('#hero-scene').getAttribute('data-scene-state'), 'ready');
  await motionPage.locator('#scene-toggle').click();
  assert.equal(await motionPage.locator('#hero-scene').getAttribute('data-motion'), 'paused');
  const pausedFrames = await motionPage.locator('#hero-scene').getAttribute('data-frames');
  await motionPage.waitForTimeout(200);
  assert.equal(await motionPage.locator('#hero-scene').getAttribute('data-frames'), pausedFrames);
  await motionPage.locator('#scene-toggle').click();
  await motionPage.evaluate(() => window.scrollTo(0, document.querySelector('#resources').offsetTop + 500));
  await motionPage.waitForFunction(() => document.querySelector('#hero-scene').dataset.motion === 'idle');
  await motionPage.evaluate(() => window.scrollTo(0, 0));
  await motionPage.waitForFunction(() => document.querySelector('#hero-scene').dataset.motion === 'running');
  await motionPage.screenshot({ path: '.qa/home-animated.png' });
  await motionPage.emulateMedia({ reducedMotion: 'reduce' });
  await motionPage.waitForFunction(() => document.querySelector('#hero-scene').dataset.motion === 'reduced');
  assert.equal(await motionPage.locator('#scene-toggle').isVisible(), false);
  await motionPage.locator('[data-theme-toggle]').first().click();
  await motionPage.waitForFunction(() => getComputedStyle(document.body).backgroundColor === 'rgb(248, 250, 252)');
  await motionPage.waitForFunction(() => getComputedStyle(document.querySelector('.home-intro h1')).color === 'rgb(15, 23, 42)');
  await motionPage.screenshot({ path: '.qa/home-light.png' });
  assert.deepEqual(motionErrors, []);
  await motionContext.close();
  await page.reload(); await page.waitForSelector('#navbar');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error('Storage blocked'); };
    Storage.prototype.setItem = () => { throw new Error('Storage blocked'); };
    const getContext = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function(type, ...args) { return /webgl/.test(type) ? null : getContext.call(this, type, ...args); };
  });
  const blockedPage = await blocked.newPage();
  const blockedErrors = [];
  blockedPage.on('pageerror', error => blockedErrors.push(error.message));
  await blockedPage.goto('http://127.0.0.1:8123/');
  await blockedPage.waitForSelector('#navbar');
  await blockedPage.waitForFunction(() => document.querySelector('#hero-scene').dataset.sceneState === 'fallback');
  assert.equal(await blockedPage.locator('#scene-toggle').isVisible(), false);
  await blockedPage.locator('#navbar [data-site-search]').first().click();
  assert.equal(await blockedPage.locator('.command-dialog').evaluate(el => el.open), true);
  assert.deepEqual(blockedErrors, []);
  await blocked.close();
  assert.deepEqual(errors, []);
  await browser.close();
  server.close();
  console.log(`PASS: search, reviews, saved resources, reading tools, contact failure/success, mobile menu, desk explorer, 3D motion controls/fallback, and ${files.length} pages at two viewport sizes.`);
})().catch(error => { console.error(error); process.exit(1); });
